### ISSUE TITLE
geo location

### ISSUE THREAD

**Issue by obaidmuneer** [MrMuhammadHussain/WeatherApp#2]
`if (window.navigator.geolocation) {
    const successfulLookup = position => {
        let { latitude, longitude } = position.coords;
        getData(latitude, longitude)
    }

    window.navigator.geolocation
        .getCurrentPosition(successfulLookup, console.log);
}`

https://www.w3schools.com/html/html5_geolocation.asp
https://www.spatialtimes.com/2022/01/using-javascripts-geolocation-api/

**Comment by MrMuhammadHussain** [comment]
i will slove as soon as posibale
Thanks
